### ISSUE TITLE
Visiting various sites gives 502 bad gateway

### ISSUE THREAD

**Issue by vysecurity** [Sprocket-Security/gigaproxy#2]
Various sites such as www.google.com is giving me 502 bad gateway...?

```
HTTP/2.0 502 Bad Gateway 36b
```

**Comment by Nishantbhagat57** [comment]
+1 
![Screenshot 2024-07-16 171217](https://github.com/user-attachments/assets/d9113684-762a-488c-b6c6-9b6cb8dec705)

**Comment by puzzlepeaches** [comment]
@vysecurity, is this on all requests for you, or is it just intermittent?

**Comment by Nishantbhagat57** [comment]
> @vysecurity, is this on all requests for you, or is it just intermittent?

For me it only works with http:// sites, it gives cert errors on https:// sites

![Screenshot 2024-07-16 174556](https://github.com/user-attachments/assets/3a15eb05-f0f1-427c-9f77-e0f8c0579aaf)

**Comment by puzzlepeaches** [comment]
> > @vysecurity, is this on all requests for you, or is it just intermittent?
> 
> For me it only works with http:// sites, it gives cert errors on https:// sites
> 
> ![Screenshot 2024-07-16 174556](https://private-user-images.githubusercontent.com/64642374/349078221-3a15eb05-f0f1-427c-9f77-e0f8c0579aaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzI2MDEsIm5iZiI6MTcyMTEzMjMwMSwicGF0aCI6Ii82NDY0MjM3NC8zNDkwNzgyMjEtM2ExNWViMDUtZjBmMS00MjdjLTlmNzctZTBmOGMwNTc5YWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEyMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjM0MTUwNTUwMGFiMDcyMDMwY2RkOTI2OGQxYjQ2ODVkYjQ2N2NlYzE4ZDhkODQ3OWNlM2QyMzEzZDU4MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwcU84l5NE7_vQ-YhOQDtx4-DbfN6AtatT7lQAj94tQ)

Did you properly install the certificates for mitmproxy before running? @Nishantbhagat57

**Comment by vysecurity** [comment]
I reckon it's to do with anti domain fronting with SNI. For example Google and cloud front has those in place so the proxy doesn't know how to correct it?

But "all requests" is the answer.

**Comment by Nishantbhagat57** [comment]
> Did you properly install the certificates for mitmproxy before running? @Nishantbhagat57 MIght want to split this into a seperate issue, your problem looks potentially unrelated to @vysecurity 's.

![Screenshot 2024-07-16 175042](https://github.com/user-attachments/assets/80eeeed8-25fb-47ed-a373-65865096859f)

**Comment by vysecurity** [comment]
The first issue and screenshot he posted looks like the issue I have. Otherscreenshots  not sure.

**Comment by puzzlepeaches** [comment]
> I reckon it's to do with anti domain fronting with SNI. For example Google and cloud front has those in place so the proxy doesn't know how to correct it?
> 
> But "all requests" is the answer.

Looking fine on my end. Can you share a screenshot similar to the following, so I can see more details on the response being sent? 
![CleanShot 2024-07-16 at 07 23 52@2x](https://github.com/user-attachments/assets/7e03a836-703c-4551-8ba7-89022c8902e9)

**Comment by Nishantbhagat57** [comment]
@puzzlepeaches These two issues seem to be linked in some way.

Steps to Reproduce:
1) On your vps:
`mitmdump -s gigaproxy.py --set auth_token="auth_token" --set proxy_endpoint="https://xyz.amazonaws.com/v1/gigaproxy-forwarder-function" --set block_global=false --listen-host 0.0.0.0 --listen-port 8888`

`block_global=false` allows you to access the proxy using the server's public IP.
 
2) On your local machine, use genlogin to create a new browser with the proxy set to `http://server_public_ip:8888`
3) Try to access http://getip.pro/ It will work without any issues. However, when you try to access https://getip.pro/ you will receive the following error: `{"message": "Internal server error"}`. Also check mitmdump logs: `<< HTTP/2.0 502 Bad Gateway 36b`

**Comment by Hogman-the-Intruder** [comment]
Hi @Nishantbhagat57

You mentioned you're running the mitmdump utility on a VPS. Which provider are you using?

**Comment by Nishantbhagat57** [comment]
> Hi @Nishantbhagat57
> 
> You mentioned you're running the mitmdump utility on a VPS. Which provider are you using? 

Netcup

**Comment by Hogman-the-Intruder** [comment]
Not able to repro if running mitmproxy locally on my Windows 10 desktop. I'll try running mitmproxy on an EC2 instance and see if the same issue pops up 

![image](https://github.com/user-attachments/assets/9d744efc-03b9-4e99-92cb-d0fd7af65c3d)

**Comment by Hogman-the-Intruder** [comment]
Wait a second. @Nishantbhagat57 in your first screenshot, can you take another screenshot but with the full output? I think I see the problem

The one in this comment -> https://github.com/Sprocket-Security/gigaproxy/issues/2#issuecomment-2230730060

**Comment by Hogman-the-Intruder** [comment]
~~Wait a second. @Nishantbhagat57 in your first screenshot, can you take another screenshot but with the full output? I think I see at least one of the problems.~~

~~The one in this comment -> https://github.com/Sprocket-Security/gigaproxy/issues/2#issuecomment-2230730060~~

Nevermind, I thought I was able to repro this when running mitmproxy on a fresh Ubuntu 22.04 in AWS, but it's working as expected on my end.

@Nishantbhagat57 I would recommend trying to run mitmproxy locally or on another netcup instance (or another provider) to see if that solves the problem. When was that instance last updated as well? I see an unexpected OpenSSL "no such file or directory" error in one of the screenshots you posted:
![gigaproxy-testing1](https://github.com/user-attachments/assets/9f829c43-1655-4359-8740-591448efea1b)



Here's the output from my own tests:

![Capture](https://github.com/user-attachments/assets/90ecabfe-a4f1-45aa-88f6-b501776e6f41)
![image](https://github.com/user-attachments/assets/a6899783-f921-4bbf-86c2-06151c241cf3)

**Comment by puzzlepeaches** [comment]
The issue was resolved outside of this thread. @Nishantbhagat57, please create a separate issue if you would like to perform further troubleshooting.

**Comment by HexHunter01** [comment]
Hi!
I have the same issue.
I followed the instructions and installed all certificates
Tried on the following systems:
1) WSL with kali
2) VPS with Ubuntu 24.04 

On the linux servers, I accessed the proxy via proxychains4.
I also installed certificates in firefox and to host system of WSL.

The proxy behavior is quite strange (google isn't the only exception):
![Screenshot_4](https://github.com/user-attachments/assets/69554d30-3b80-4e99-87ba-c1362d314f9d)

More interesting is this situation: in the first two screenshots, the request is made to twitch from browser, and in the next two via proxychains4 from the server.
![1](https://github.com/user-attachments/assets/ae953b19-f972-4d9f-835f-a15e2ff3b305)
![2](https://github.com/user-attachments/assets/db272b62-7577-4957-8ec7-0b3878356ac7)

--- 
![3](https://github.com/user-attachments/assets/8e3065fe-69f6-4cab-b660-b21ee6d5f057)
![4](https://github.com/user-attachments/assets/758c8b08-27c9-46dd-b29f-799c71010b80)



This is what happens when I try to access facebook.com from firefox:

![image](https://github.com/user-attachments/assets/e22c5d9f-02f6-42c9-8e0b-bffcca94cc31)

Tried running it through python:
```python
import requests

r = requests.get('https://github.com')
print(r.text)
```

But I get the error `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`.

Although certificates are added to the correct directory: `DefaultVerifyPaths(cafile='/usr/lib/ssl/cert.pem', capath='/usr/lib/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert. pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')` and updated via `update-ca-certificates`.


It is worth noting that there are no problems with http.

**Comment by moscowchill** [comment]
The idea seemed ok but this has a lot of problems
